name: Build and Test

on:
  push:
    branches-ignore:
      - "no-ci-*"
  pull_request:
    branches:
      - "**"

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"
  VCPKG_NUGET_REPOSITORY: https://github.com/mapnik/vcpkg-cache.git

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
        include:
          - os: "windows-latest"
            mono: ""
            preset: "windows-ci"
          - os: "ubuntu-latest"
            mono: "mono"
            preset: "linux-ci"
          - os: "macos-latest"
            mono: "mono"
            preset: "macos-ci"

    steps:
      - name: checkout mapnik
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: "microsoft/vcpkg"
          ref: 2e34a79a814551424d9b1a981b3b110e0a8fbdfd
          path: vcpkg

      - name: "Setup vcpkg"
        shell: bash
        run:   |
         if [ "$RUNNER_OS" == "Windows" ]; then
              ./vcpkg/bootstrap-vcpkg.bat
         else
              ./vcpkg/bootstrap-vcpkg.sh
         fi

      - name: "Setup NuGet Credentials"
        shell: "bash"
        run: >
          ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/mapnik/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "mapnik"
          -password "${{ secrets.VCPKG_CACHE_PAT }}"

      - name: "Setup NuGet apikey"
        shell: "bash"
        run: >
          ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
          setapikey "${{ secrets.VCPKG_CACHE_PAT }}" -Source "https://nuget.pkg.github.com/mapnik/index.json"

      - name: Configure CMake
        run: cmake -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake --preset=${{ matrix.preset }}
